Ftdi::Context
Direction
ModemCtl
friend class Eeprom
friend class List
boost::shared_ptr<Private> Ftdi::Context::d
Ftdi::Context::Context()
Constructor.
Ftdi::Context::~Context()
Destructor.
Eeprom* Ftdi::Context::eeprom()
const std::string & Ftdi::Context::vendor()
Device strings properties.
Referenced by get_strings.
const std::string & Ftdi::Context::description()
Device strings properties.
const std::string & Ftdi::Context::serial()
Device strings properties.
Referenced by get_strings.
bool Ftdi::Context::is_open()
int Ftdi::Context::open(struct libusb_device *dev=0)
References get_strings_and_reopen.
int Ftdi::Context::open(int vendor, int product)
References ftdi_usb_open, get_strings_and_reopen.
int Ftdi::Context::open(int vendor, int product, const std::string &description, const std::string &serial=std::string(), unsigned int index=0)
References ftdi_usb_open_desc_index, get_strings_and_reopen.
int Ftdi::Context::open(const std::string &description)
References ftdi_usb_open_string, get_strings_and_reopen.
int Ftdi::Context::close()
References ftdi_usb_close.
int Ftdi::Context::reset()
References ftdi_usb_reset.
int Ftdi::Context::flush(int mask=Input|Output)
References ftdi_usb_purge_rx_buffer, ftdi_usb_purge_tx_buffer, Input, Output.
int Ftdi::Context::set_interface(enum ftdi_interface interface)
References ftdi_set_interface.
void Ftdi::Context::set_usb_device(struct libusb_device_handle *dev)
References ftdi_set_usbdev.
Referenced by Ftdi::List::List.
int Ftdi::Context::set_baud_rate(int baudrate)
References ftdi_set_baudrate.
int Ftdi::Context::set_line_property(enum ftdi_bits_type bits, enum ftdi_stopbits_type sbit, enum ftdi_parity_type parity)
References ftdi_set_line_property.
int Ftdi::Context::set_line_property(enum ftdi_bits_type bits, enum ftdi_stopbits_type sbit, enum ftdi_parity_type parity, enum ftdi_break_type break_type)
References ftdi_set_line_property2.
int Ftdi::Context::read(unsigned char *buf, int size)
References ftdi_read_data.
int Ftdi::Context::write(unsigned char *buf, int size)
References ftdi_write_data.
int Ftdi::Context::set_read_chunk_size(unsigned int chunksize)
References ftdi_read_data_set_chunksize.
int Ftdi::Context::set_write_chunk_size(unsigned int chunksize)
References ftdi_write_data_set_chunksize.
int Ftdi::Context::read_chunk_size()
References ftdi_read_data_get_chunksize.
int Ftdi::Context::write_chunk_size()
References ftdi_write_data_get_chunksize.
int Ftdi::Context::set_event_char(unsigned char eventch, unsigned char enable)
References ftdi_set_event_char.
int Ftdi::Context::set_error_char(unsigned char errorch, unsigned char enable)
References ftdi_set_error_char.
int Ftdi::Context::set_flow_control(int flowctrl)
References ftdi_setflowctrl.
int Ftdi::Context::set_modem_control(int mask=Dtr|Rts)
References Dtr, ftdi_setdtr_rts, Rts.
int Ftdi::Context::set_latency(unsigned char latency)
References ftdi_set_latency_timer.
int Ftdi::Context::set_dtr(bool state)
References ftdi_setdtr.
int Ftdi::Context::set_rts(bool state)
References ftdi_setrts.
unsigned short Ftdi::Context::poll_modem_status()
References ftdi_poll_modem_status.
unsigned Ftdi::Context::latency()
References ftdi_get_latency_timer.
int Ftdi::Context::set_bitmode(unsigned char bitmask, unsigned char mode)
References ftdi_set_bitmode.
int Ftdi::Context::set_bitmode(unsigned char bitmask, enum ftdi_mpsse_mode mode)
References ftdi_set_bitmode.
int Ftdi::Context::bitbang_disable()
References ftdi_disable_bitbang.
int Ftdi::Context::read_pins(unsigned char *pins)
References ftdi_read_pins.
char * Ftdi::Context::error_string()
References ftdi_get_error_string.
int Ftdi::Context::get_strings()
References ftdi_usb_get_strings, serial, vendor.
Referenced by get_strings_and_reopen, Ftdi::List::List.
int Ftdi::Context::get_strings_and_reopen()
References ftdi_usb_open_dev, get_strings.
Referenced by open.
struct ftdi_context * Ftdi::Context::context()
Referenced by Ftdi::Eeprom::Eeprom, Ftdi::List::find_all, set_context.
void Ftdi::Context::set_context(struct ftdi_context *context)
References context, ftdi_free.
void Ftdi::Context::set_usb_device(struct libusb_device *dev)