ftdi.h
MPSSE_WRITE_NEG
MPSSE_BITMODE
MPSSE_READ_NEG
MPSSE_LSB
MPSSE_DO_WRITE
MPSSE_DO_READ
MPSSE_WRITE_TMS
SET_BITS_LOW
SET_BITS_HIGH
GET_BITS_LOW
GET_BITS_HIGH
LOOPBACK_START
LOOPBACK_END
TCK_DIVISOR
DIS_DIV_5
EN_DIV_5
EN_3_PHASE
DIS_3_PHASE
CLK_BITS
CLK_BYTES
CLK_WAIT_HIGH
CLK_WAIT_LOW
EN_ADAPTIVE
DIS_ADAPTIVE
CLK_BYTES_OR_HIGH
CLK_BYTES_OR_LOW
DRIVE_OPEN_COLLECTOR
DIV_VALUE
SEND_IMMEDIATE
WAIT_ON_HIGH
WAIT_ON_LOW
READ_SHORT
READ_EXTENDED
WRITE_SHORT
WRITE_EXTENDED
SIO_RESET
SIO_MODEM_CTRL
SIO_SET_FLOW_CTRL
SIO_SET_BAUD_RATE
SIO_SET_DATA
FTDI_DEVICE_OUT_REQTYPE
Referenced by ftdi_disable_bitbang, ftdi_erase_eeprom, ftdi_set_baudrate, ftdi_set_bitmode, ftdi_set_error_char, ftdi_set_event_char, ftdi_set_latency_timer, ftdi_set_line_property2, ftdi_setdtr, ftdi_setdtr_rts, ftdi_setflowctrl, ftdi_setrts, ftdi_usb_purge_rx_buffer, ftdi_usb_purge_tx_buffer, ftdi_usb_reset, ftdi_write_eeprom, ftdi_write_eeprom_location.
FTDI_DEVICE_IN_REQTYPE
Referenced by ftdi_get_latency_timer, ftdi_poll_modem_status, ftdi_read_chipid, ftdi_read_eeprom, ftdi_read_eeprom_location, ftdi_read_pins.
SIO_RESET_REQUEST
Referenced by ftdi_usb_purge_rx_buffer, ftdi_usb_purge_tx_buffer, ftdi_usb_reset.
SIO_SET_BAUDRATE_REQUEST
Referenced by ftdi_set_baudrate.
SIO_SET_DATA_REQUEST
Referenced by ftdi_set_line_property2.
SIO_SET_FLOW_CTRL_REQUEST
Referenced by ftdi_setflowctrl.
SIO_SET_MODEM_CTRL_REQUEST
Referenced by ftdi_setdtr, ftdi_setdtr_rts, ftdi_setrts.
SIO_POLL_MODEM_STATUS_REQUEST
Referenced by ftdi_poll_modem_status.
SIO_SET_EVENT_CHAR_REQUEST
Referenced by ftdi_set_event_char.
SIO_SET_ERROR_CHAR_REQUEST
Referenced by ftdi_set_error_char.
SIO_SET_LATENCY_TIMER_REQUEST
Referenced by ftdi_set_latency_timer.
SIO_GET_LATENCY_TIMER_REQUEST
Referenced by ftdi_get_latency_timer.
SIO_SET_BITMODE_REQUEST
Referenced by ftdi_disable_bitbang, ftdi_set_bitmode.
SIO_READ_PINS_REQUEST
Referenced by ftdi_read_pins.
SIO_READ_EEPROM_REQUEST
Referenced by ftdi_read_chipid, ftdi_read_eeprom, ftdi_read_eeprom_location.
SIO_WRITE_EEPROM_REQUEST
Referenced by ftdi_erase_eeprom, ftdi_write_eeprom, ftdi_write_eeprom_location.
SIO_ERASE_EEPROM_REQUEST
Referenced by ftdi_erase_eeprom.
SIO_RESET_SIO
Referenced by ftdi_usb_reset.
SIO_RESET_PURGE_RX
Referenced by ftdi_usb_purge_rx_buffer.
SIO_RESET_PURGE_TX
Referenced by ftdi_usb_purge_tx_buffer.
SIO_DISABLE_FLOW_CTRL
SIO_RTS_CTS_HS
SIO_DTR_DSR_HS
SIO_XON_XOFF_HS
SIO_SET_DTR_MASK
SIO_SET_DTR_HIGH
Referenced by ftdi_setdtr, ftdi_setdtr_rts.
SIO_SET_DTR_LOW
Referenced by ftdi_setdtr, ftdi_setdtr_rts.
SIO_SET_RTS_MASK
SIO_SET_RTS_HIGH
Referenced by ftdi_setdtr_rts, ftdi_setrts.
SIO_SET_RTS_LOW
Referenced by ftdi_setdtr_rts, ftdi_setrts.
SIO_RTS_CTS_HS
FTDI_URB_USERCONTEXT_COOKIE
DEPRECATED
FT1284_CLK_IDLE_STATE
Referenced by ftdi_eeprom_build, ftdi_eeprom_decode.
FT1284_DATA_LSB
Referenced by ftdi_eeprom_build, ftdi_eeprom_decode.
FT1284_FLOW_CONTROL
Referenced by ftdi_eeprom_build, ftdi_eeprom_decode.
POWER_SAVE_DISABLE_H
Referenced by ftdi_eeprom_build, ftdi_eeprom_decode.
USE_SERIAL_NUM
Referenced by ftdi_eeprom_build, ftdi_eeprom_decode.
INVERT_TXD
Invert TXD#
INVERT_RXD
Invert RXD#
INVERT_RTS
Invert RTS#
INVERT_CTS
Invert CTS#
INVERT_DTR
Invert DTR#
INVERT_DSR
Invert DSR#
INVERT_DCD
Invert DCD#
INVERT_RI
Invert RI#
CHANNEL_IS_UART
Interface Mode.
CHANNEL_IS_FIFO
CHANNEL_IS_OPTO
CHANNEL_IS_CPU
CHANNEL_IS_FT1284
CHANNEL_IS_RS485
Referenced by ftdi_eeprom_build, ftdi_eeprom_decode.
DRIVE_4MA
DRIVE_8MA
DRIVE_12MA
DRIVE_16MA
Referenced by ftdi_eeprom_build, ftdi_eeprom_decode.
SLOW_SLEW
Referenced by ftdi_eeprom_build, ftdi_eeprom_decode.
IS_SCHMITT
Referenced by ftdi_eeprom_build, ftdi_eeprom_decode.
DRIVER_VCP
Driver Type.
Referenced by ftdi_eeprom_build, ftdi_eeprom_decode.
DRIVER_VCPH
Referenced by ftdi_eeprom_build, ftdi_eeprom_decode.
USE_USB_VERSION_BIT
Referenced by ftdi_eeprom_build, ftdi_eeprom_decode.
SUSPEND_DBUS7_BIT
Referenced by ftdi_eeprom_build, ftdi_eeprom_decode.
HIGH_CURRENT_DRIVE
High current drive.
Referenced by ftdi_eeprom_build, ftdi_eeprom_decode.
HIGH_CURRENT_DRIVE_R
Referenced by ftdi_eeprom_build, ftdi_eeprom_decode.
ftdi_chip_type
ftdi_parity_type
ftdi_stopbits_type
ftdi_bits_type
ftdi_break_type
ftdi_mpsse_mode
switch off bitbang mode, back to regular serial/FIFO
ftdi_interface
ftdi_module_detach_mode
ftdi_eeprom_value
ftdi_cbus_func
ftdi_cbush_func
typedef int( FTDIStreamCallback)(uint8_t *buffer, int length, FTDIProgressInfo *progress, void *userdata))(uint8_t *buffer, int length, FTDIProgressInfo *progress, void *userdata)
int ftdi_init(struct ftdi_context *ftdi)
Initializes a ftdi_context. ftdi pointer to ftdi_context 0 : all fine -1 : couldn't allocate read buffer -2 : couldn't allocate struct buffer -3 : libusb_init() failed This should be called before all functions
References ftdi_context::usb_ctx, ftdi_context::usb_dev, ftdi_context::usb_read_timeout, ftdi_context::usb_write_timeout, ftdi_context::type, TYPE_BM, ftdi_context::baudrate, ftdi_context::bitbang_enabled, ftdi_context::readbuffer, ftdi_context::readbuffer_offset, ftdi_context::readbuffer_remaining, ftdi_context::writebuffer_chunksize, ftdi_context::max_packet_size, ftdi_context::error_str, ftdi_context::module_detach_mode, AUTO_DETACH_SIO_MODULE, ftdi_error_return, ftdi_set_interface, INTERFACE_ANY, ftdi_context::bitbang_mode, ftdi_context::eeprom, ftdi_read_data_set_chunksize.
Referenced by ftdi_new.
struct ftdi_context* ftdi_new(void)
Allocate and initialize a new ftdi_contexta pointer to a new ftdi_context, or NULL on failure
References ftdi_init.
Referenced by Ftdi::Context::Private::Private.
int ftdi_set_interface(struct ftdi_context *ftdi, enum ftdi_interface interface)
Open selected channels on a chip, otherwise use first channel. ftdi pointer to ftdi_context interface Interface to use for FT2232C/2232H/4232H chips. 0 : all fine -1 : unknown interface -2 : USB device unavailable -3 : Device already open, interface can't be set in that state
References ftdi_error_return, ftdi_context::usb_dev, ftdi_context::interface, INTERFACE_ANY, INTERFACE_A, ftdi_context::index, ftdi_context::in_ep, ftdi_context::out_ep, INTERFACE_B, INTERFACE_C, INTERFACE_D.
Referenced by ftdi_init, Ftdi::Context::set_interface.
void ftdi_deinit(struct ftdi_context *ftdi)
Deinitializes a ftdi_context. ftdi pointer to ftdi_context
References ftdi_context::readbuffer, ftdi_context::eeprom, ftdi_eeprom::manufacturer, ftdi_eeprom::product, ftdi_eeprom::serial, ftdi_context::usb_ctx.
Referenced by ftdi_free.
void ftdi_free(struct ftdi_context *ftdi)
Deinitialize and free an ftdi_context. ftdi pointer to ftdi_context
References ftdi_deinit.
Referenced by Ftdi::Context::Private::~Private, Ftdi::Context::set_context.
void ftdi_set_usbdev(struct ftdi_context *ftdi, struct libusb_device_handle *usbdev)
Use an already open libusb device. ftdi pointer to ftdi_context usb libusb libusb_device_handle to use
References ftdi_context::usb_dev.
Referenced by Ftdi::Context::set_usb_device.
struct ftdi_version_info ftdi_get_library_version()
Get libftdi library version.
ftdi_version_info Library version information
References ftdi_version_info::major, ftdi_version_info::minor, ftdi_version_info::micro, ftdi_version_info::version_str, ftdi_version_info::snapshot_str.
int ftdi_usb_find_all(struct ftdi_context *ftdi, struct ftdi_device_list **devlist, int vendor, int product)
Finds all ftdi devices with given VID:PID on the usb bus. Creates a new ftdi_device_list which needs to be deallocated by ftdi_list_free() after use. With VID:PID 0:0, search for the default devices (0x403:0x6001, 0x403:0x6010, 0x403:0x6011, 0x403:0x6014) ftdi pointer to ftdi_context devlist Pointer where to store list of found devices vendor Vendor ID to search for product Product ID to search for >0 : number of devices found -3 : out of memory -5 : libusb_get_device_list() failed -6 : libusb_get_device_descriptor() failed
References ftdi_device_list::dev, ftdi_context::usb_ctx, ftdi_error_return, ftdi_error_return_free_device_list, ftdi_device_list::next.
Referenced by Ftdi::List::find_all.
void ftdi_list_free(struct ftdi_device_list **devlist)
Frees a usb device list. devlist USB device list created by ftdi_usb_find_all()
References ftdi_device_list::next, ftdi_device_list::dev.
Referenced by ftdi_list_free2, Ftdi::List::Private::~Private, Ftdi::List::clear.
void ftdi_list_free2(struct ftdi_device_list *devlist)
Frees a usb device list. devlist USB device list created by ftdi_usb_find_all()
References ftdi_list_free.
int ftdi_usb_get_strings(struct ftdi_context *ftdi, struct libusb_device *dev, char *manufacturer, int mnf_len, char *description, int desc_len, char *serial, int serial_len)
Return device ID strings from the usb device.The parameters manufacturer, description and serial may be NULL or pointer to buffers to store the fetched strings.Use this function only in combination with ftdi_usb_find_all() as it closes the internal "usb_dev" after use. ftdi pointer to ftdi_context dev libusb usb_dev to use manufacturer Store manufacturer string here if not NULL mnf_len Buffer size of manufacturer string description Store product description string here if not NULL desc_len Buffer size of product description string serial Store serial string here if not NULL serial_len Buffer size of serial string 0 : all fine -1 : wrong arguments -4 : unable to open device -7 : get product manufacturer failed -8 : get product description failed -9 : get serial number failed -11 : libusb_get_device_descriptor() failed
References ftdi_context::usb_dev, ftdi_error_return.
Referenced by Ftdi::Context::get_strings.
int ftdi_usb_open(struct ftdi_context *ftdi, int vendor, int product)
Opens the first device with a given vendor and product ids. ftdi pointer to ftdi_context vendor Vendor ID product Product ID same as ftdi_usb_open_desc()
References ftdi_usb_open_desc.
Referenced by Ftdi::Context::open.
int ftdi_usb_open_desc(struct ftdi_context *ftdi, int vendor, int product, const char *description, const char *serial)
Opens the first device with a given, vendor id, product id, description and serial. ftdi pointer to ftdi_context vendor Vendor ID product Product ID description Description to search for. Use NULL if not needed. serial Serial to search for. Use NULL if not needed. 0 : all fine -3 : usb device not found -4 : unable to open device -5 : unable to claim device -6 : reset failed -7 : set baudrate failed -8 : get product description failed -9 : get serial number failed -12 : libusb_get_device_list() failed -13 : libusb_get_device_descriptor() failed
References ftdi_usb_open_desc_index.
Referenced by ftdi_usb_open.
int ftdi_usb_open_desc_index(struct ftdi_context *ftdi, int vendor, int product, const char *description, const char *serial, unsigned int index)
Opens the index-th device with a given, vendor id, product id, description and serial. ftdi pointer to ftdi_context vendor Vendor ID product Product ID description Description to search for. Use NULL if not needed. serial Serial to search for. Use NULL if not needed. index Number of matching device to open if there are more than one, starts with 0. 0 : all fine -1 : usb_find_busses() failed -2 : usb_find_devices() failed -3 : usb device not found -4 : unable to open device -5 : unable to claim device -6 : reset failed -7 : set baudrate failed -8 : get product description failed -9 : get serial number failed -10 : unable to close device -11 : ftdi context invalid
References ftdi_error_return, ftdi_context::usb_ctx, ftdi_error_return_free_device_list, ftdi_context::usb_dev, ftdi_usb_open_dev.
Referenced by ftdi_usb_open_desc, ftdi_usb_open_string, Ftdi::Context::open.
int ftdi_usb_open_dev(struct ftdi_context *ftdi, struct libusb_device *dev)
Opens a ftdi device given by an usb_device. ftdi pointer to ftdi_context dev libusb usb_dev to use 0 : all fine -3 : unable to config device -4 : unable to open device -5 : unable to claim device -6 : reset failed -7 : set baudrate failed -8 : ftdi context invalid -9 : libusb_get_device_descriptor() failed -10 : libusb_get_config_descriptor() failed -11 : libusb_detach_kernel_driver() failed -12 : libusb_get_configuration() failed
References ftdi_error_return, ftdi_context::usb_dev, ftdi_context::module_detach_mode, AUTO_DETACH_SIO_MODULE, ftdi_context::interface, ftdi_usb_reset, ftdi_context::type, TYPE_BM, TYPE_AM, TYPE_2232C, TYPE_R, TYPE_2232H, TYPE_4232H, TYPE_232H, ftdi_context::max_packet_size, ftdi_set_baudrate.
Referenced by ftdi_usb_open_desc_index, ftdi_usb_open_string, Ftdi::Context::get_strings_and_reopen.
int ftdi_usb_open_string(struct ftdi_context *ftdi, const char *description)
Opens the ftdi-device described by a description-string. Intended to be used for parsing a device-description given as commandline argument. ftdi pointer to ftdi_context description NULL-terminated description-string, using this format: d:<devicenode> path of bus and device-node (e.g. "003/001") within usb device tree (usually at /proc/bus/usb/) i:<vendor>:<product> first device with given vendor and product id, ids can be decimal, octal (preceded by "0") or hex (preceded by "0x") i:<vendor>:<product>:<index> as above with index being the number of the device (starting with 0) if there are more than one s:<vendor>:<product>:<serial> first device with given vendor id, product id and serial string The description format may be extended in later versions. 0 : all fine -2 : libusb_get_device_list() failed -3 : usb device not found -4 : unable to open device -5 : unable to claim device -6 : reset failed -7 : set baudrate failed -8 : get product description failed -9 : get serial number failed -10 : unable to close device -11 : illegal description format -12 : ftdi context invalid
References ftdi_error_return, ftdi_context::usb_ctx, ftdi_error_return_free_device_list, ftdi_usb_open_dev, ftdi_usb_open_desc_index.
Referenced by Ftdi::Context::open.
int ftdi_usb_close(struct ftdi_context *ftdi)
Closes the ftdi device. Call ftdi_deinit() if you're cleaning up. ftdi pointer to ftdi_context 0 : all fine -1 : usb_release failed -3 : ftdi context invalid
References ftdi_error_return, ftdi_context::usb_dev, ftdi_context::interface.
Referenced by Ftdi::Context::Private::~Private, Ftdi::Context::close.
int ftdi_usb_reset(struct ftdi_context *ftdi)
Resets the ftdi device. ftdi pointer to ftdi_context 0 : all fine -1 : FTDI reset failed -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, FTDI_DEVICE_OUT_REQTYPE, SIO_RESET_REQUEST, SIO_RESET_SIO, ftdi_context::index, ftdi_context::usb_write_timeout, ftdi_context::readbuffer_offset, ftdi_context::readbuffer_remaining.
Referenced by ftdi_usb_open_dev, ftdi_write_eeprom, Ftdi::Context::reset.
int ftdi_usb_purge_rx_buffer(struct ftdi_context *ftdi)
Clears the read buffer on the chip and the internal read buffer. ftdi pointer to ftdi_context 0 : all fine -1 : read buffer purge failed -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, FTDI_DEVICE_OUT_REQTYPE, SIO_RESET_REQUEST, SIO_RESET_PURGE_RX, ftdi_context::index, ftdi_context::usb_write_timeout, ftdi_context::readbuffer_offset, ftdi_context::readbuffer_remaining.
Referenced by ftdi_usb_purge_buffers, Ftdi::Context::flush.
int ftdi_usb_purge_tx_buffer(struct ftdi_context *ftdi)
Clears the write buffer on the chip. ftdi pointer to ftdi_context 0 : all fine -1 : write buffer purge failed -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, FTDI_DEVICE_OUT_REQTYPE, SIO_RESET_REQUEST, SIO_RESET_PURGE_TX, ftdi_context::index, ftdi_context::usb_write_timeout.
Referenced by ftdi_usb_purge_buffers, Ftdi::Context::flush.
int ftdi_usb_purge_buffers(struct ftdi_context *ftdi)
Clears the buffers on the chip and the internal read buffer. ftdi pointer to ftdi_context 0 : all fine -1 : read buffer purge failed -2 : write buffer purge failed -3 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, ftdi_usb_purge_rx_buffer, ftdi_usb_purge_tx_buffer.
Referenced by ftdi_readstream.
int ftdi_set_baudrate(struct ftdi_context *ftdi, int baudrate)
Sets the chip baud rate ftdi pointer to ftdi_context baudrate baud rate to set 0 : all fine -1 : invalid baudrate -2 : setting baudrate failed -3 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, ftdi_context::bitbang_enabled, FTDI_DEVICE_OUT_REQTYPE, SIO_SET_BAUDRATE_REQUEST, ftdi_context::usb_write_timeout, ftdi_context::baudrate.
Referenced by ftdi_usb_open_dev, Ftdi::Context::set_baud_rate.
int ftdi_set_line_property(struct ftdi_context *ftdi, enum ftdi_bits_type bits, enum ftdi_stopbits_type sbit, enum ftdi_parity_type parity)
Set (RS232) line characteristics. The break type can only be set via ftdi_set_line_property2() and defaults to "off". ftdi pointer to ftdi_context bits Number of bits sbit Number of stop bits parity Parity mode 0 : all fine -1 : Setting line property failed
References ftdi_set_line_property2, BREAK_OFF.
Referenced by Ftdi::Context::set_line_property.
int ftdi_set_line_property2(struct ftdi_context *ftdi, enum ftdi_bits_type bits, enum ftdi_stopbits_type sbit, enum ftdi_parity_type parity, enum ftdi_break_type break_type)
Set (RS232) line characteristics ftdi pointer to ftdi_context bits Number of bits sbit Number of stop bits parity Parity mode break_type Break type 0 : all fine -1 : Setting line property failed -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, NONE, ODD, EVEN, MARK, SPACE, STOP_BIT_1, STOP_BIT_15, STOP_BIT_2, BREAK_OFF, BREAK_ON, FTDI_DEVICE_OUT_REQTYPE, SIO_SET_DATA_REQUEST, ftdi_context::index, ftdi_context::usb_write_timeout.
Referenced by ftdi_set_line_property, Ftdi::Context::set_line_property.
int ftdi_read_data(struct ftdi_context *ftdi, unsigned char *buf, int size)
Reads data in chunks (see ftdi_read_data_set_chunksize()) from the chip.Automatically strips the two modem status bytes transfered during every read. ftdi pointer to ftdi_context buf Buffer to store data in size Size of the buffer -666 : USB device unavailable <0 : error code from libusb_bulk_transfer() 0 : no data was available >0 : number of bytes read
References ftdi_transfer_control::offset, ftdi_context::max_packet_size, ftdi_context::usb_dev, ftdi_error_return, ftdi_context::readbuffer, ftdi_context::readbuffer_offset, ftdi_context::readbuffer_remaining, ftdi_transfer_control::size, ftdi_context::out_ep, ftdi_context::readbuffer_chunksize, ftdi_context::usb_read_timeout.
Referenced by Ftdi::Context::read.
int ftdi_read_data_set_chunksize(struct ftdi_context *ftdi, unsigned int chunksize)
Configure read buffer chunk size. Default is 4096.Automatically reallocates the buffer. ftdi pointer to ftdi_context chunksize Chunk size 0 : all fine -1 : ftdi context invalid
References ftdi_error_return, ftdi_context::readbuffer_offset, ftdi_context::readbuffer_remaining, ftdi_context::readbuffer, ftdi_context::readbuffer_chunksize.
Referenced by ftdi_init, Ftdi::Context::set_read_chunk_size.
int ftdi_read_data_get_chunksize(struct ftdi_context *ftdi, unsigned int *chunksize)
Get read buffer chunk size. ftdi pointer to ftdi_context chunksize Pointer to store chunk size in 0 : all fine -1 : FTDI context invalid
References ftdi_error_return, ftdi_context::readbuffer_chunksize.
Referenced by Ftdi::Context::read_chunk_size.
int ftdi_write_data(struct ftdi_context *ftdi, unsigned char *buf, int size)
Writes data in chunks (see ftdi_write_data_set_chunksize()) to the chip ftdi pointer to ftdi_context buf Buffer with the data size Size of the buffer -666 : USB device unavailable <0 : error code from usb_bulk_write() >0 : number of bytes written
References ftdi_context::usb_dev, ftdi_error_return, ftdi_context::writebuffer_chunksize, ftdi_context::in_ep, ftdi_context::usb_write_timeout.
Referenced by Ftdi::Context::write.
int ftdi_write_data_set_chunksize(struct ftdi_context *ftdi, unsigned int chunksize)
Configure write buffer chunk size. Default is 4096. ftdi pointer to ftdi_context chunksize Chunk size 0 : all fine -1 : ftdi context invalid
References ftdi_error_return, ftdi_context::writebuffer_chunksize.
Referenced by Ftdi::Context::set_write_chunk_size.
int ftdi_write_data_get_chunksize(struct ftdi_context *ftdi, unsigned int *chunksize)
Get write buffer chunk size. ftdi pointer to ftdi_context chunksize Pointer to store chunk size in 0 : all fine -1 : ftdi context invalid
References ftdi_error_return, ftdi_context::writebuffer_chunksize.
Referenced by Ftdi::Context::write_chunk_size.
int ftdi_readstream(struct ftdi_context *ftdi, FTDIStreamCallback *callback, void *userdata, int packetsPerTransfer, int numTransfers)
Streaming reading of data from the deviceUse asynchronous transfers in libusb-1.0 for high-performance streaming of data from a device interface back to the PC. This function continuously transfers data until either an error occurs or the callback returns a nonzero value. This function returns a libusb error code or the callback's return value.For every contiguous block of received data, the callback will be invoked. ftdi pointer to ftdi_context callback to user supplied function for one block of data userdata packetsPerTransfer number of packets per transfer numTransfers Number of transfers per callback
References FTDIStreamState::activity, BITMODE_RESET, BITMODE_SYNCFF, FTDIStreamState::callback, FTDIProgressInfo::current, FTDIProgressInfo::currentRate, FTDIProgressInfo::first, ftdi_get_error_string, ftdi_set_bitmode, ftdi_usb_purge_buffers, ftdi_context::max_packet_size, ftdi_context::out_ep, FTDIProgressInfo::prev, FTDIStreamState::progress, FTDIStreamState::result, size_and_time::time, size_and_time::totalBytes, FTDIProgressInfo::totalRate, FTDIProgressInfo::totalTime, ftdi_context::type, TYPE_2232H, TYPE_232H, ftdi_context::usb_ctx, ftdi_context::usb_dev, ftdi_context::usb_read_timeout, FTDIStreamState::userdata.
struct ftdi_transfer_control* ftdi_write_data_submit(struct ftdi_context *ftdi, unsigned char *buf, int size)
Writes data to the chip. Does not wait for completion of the transfer nor does it make sure that the transfer was successful.Use libusb 1.0 asynchronous API. ftdi pointer to ftdi_context buf Buffer with the data size Size of the buffer NULL : Some error happens when submit transfer !NULL : Pointer to a ftdi_transfer_control
References ftdi_context::usb_dev, ftdi_transfer_control::ftdi, ftdi_transfer_control::completed, ftdi_transfer_control::buf, ftdi_transfer_control::size, ftdi_transfer_control::offset, ftdi_context::writebuffer_chunksize, ftdi_context::in_ep, ftdi_context::usb_write_timeout, ftdi_transfer_control::transfer.
struct ftdi_transfer_control* ftdi_read_data_submit(struct ftdi_context *ftdi, unsigned char *buf, int size)
Reads data from the chip. Does not wait for completion of the transfer nor does it make sure that the transfer was successful.Use libusb 1.0 asynchronous API. ftdi pointer to ftdi_context buf Buffer with the data size Size of the buffer NULL : Some error happens when submit transfer !NULL : Pointer to a ftdi_transfer_control
References ftdi_context::usb_dev, ftdi_transfer_control::ftdi, ftdi_transfer_control::buf, ftdi_transfer_control::size, ftdi_context::readbuffer, ftdi_context::readbuffer_offset, ftdi_context::readbuffer_remaining, ftdi_transfer_control::completed, ftdi_transfer_control::offset, ftdi_transfer_control::transfer, ftdi_context::out_ep, ftdi_context::readbuffer_chunksize, ftdi_context::usb_read_timeout.
int ftdi_transfer_data_done(struct ftdi_transfer_control *tc)
Wait for completion of the transfer.Use libusb 1.0 asynchronous API. tc pointer to ftdi_transfer_control < 0: Some error happens >= 0: Data size transferred
References ftdi_transfer_control::completed, ftdi_transfer_control::ftdi, ftdi_context::usb_ctx, ftdi_transfer_control::transfer, ftdi_transfer_control::offset.
int ftdi_set_bitmode(struct ftdi_context *ftdi, unsigned char bitmask, unsigned char mode)
Enable/disable bitbang modes. ftdi pointer to ftdi_context bitmask Bitmask to configure lines. HIGH/ON value configures a line as output. mode Bitbang mode: use the values defined in ftdi_mpsse_mode 0 : all fine -1 : can't enable bitbang mode -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, FTDI_DEVICE_OUT_REQTYPE, SIO_SET_BITMODE_REQUEST, ftdi_context::index, ftdi_context::usb_write_timeout, ftdi_context::bitbang_mode, ftdi_context::bitbang_enabled, BITMODE_RESET.
Referenced by Ftdi::Context::set_bitmode, ftdi_readstream.
int ftdi_disable_bitbang(struct ftdi_context *ftdi)
Disable bitbang mode. ftdi pointer to ftdi_context 0 : all fine -1 : can't disable bitbang mode -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, FTDI_DEVICE_OUT_REQTYPE, SIO_SET_BITMODE_REQUEST, ftdi_context::index, ftdi_context::usb_write_timeout, ftdi_context::bitbang_enabled.
Referenced by Ftdi::Context::bitbang_disable.
int ftdi_read_pins(struct ftdi_context *ftdi, unsigned char *pins)
Directly read pin state, circumventing the read buffer. Useful for bitbang mode. ftdi pointer to ftdi_context pins Pointer to store pins into 0 : all fine -1 : read pins failed -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, FTDI_DEVICE_IN_REQTYPE, SIO_READ_PINS_REQUEST, ftdi_context::index, ftdi_context::usb_read_timeout.
Referenced by Ftdi::Context::read_pins.
int ftdi_set_latency_timer(struct ftdi_context *ftdi, unsigned char latency)
Set latency timerThe FTDI chip keeps data in the internal buffer for a specific amount of time if the buffer is not full yet to decrease load on the usb bus. ftdi pointer to ftdi_context latency Value between 1 and 255 0 : all fine -1 : latency out of range -2 : unable to set latency timer -3 : USB device unavailable
References ftdi_error_return, ftdi_context::usb_dev, FTDI_DEVICE_OUT_REQTYPE, SIO_SET_LATENCY_TIMER_REQUEST, ftdi_context::index, ftdi_context::usb_write_timeout.
Referenced by ftdi_write_eeprom, Ftdi::Context::set_latency.
int ftdi_get_latency_timer(struct ftdi_context *ftdi, unsigned char *latency)
Get latency timer ftdi pointer to ftdi_context latency Pointer to store latency value in 0 : all fine -1 : unable to get latency timer -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, FTDI_DEVICE_IN_REQTYPE, SIO_GET_LATENCY_TIMER_REQUEST, ftdi_context::index, ftdi_context::usb_read_timeout.
Referenced by Ftdi::Context::latency.
int ftdi_poll_modem_status(struct ftdi_context *ftdi, unsigned short *status)
Poll modem status informationThis function allows the retrieve the two status bytes of the device. The device sends these bytes also as a header for each read access where they are discarded by ftdi_read_data(). The chip generates the two stripped status bytes in the absence of data every 40 ms.Layout of the first byte: B0..B3 - must be 0B4 Clear to send (CTS) 0 = inactive 1 = activeB5 Data set ready (DTS) 0 = inactive 1 = activeB6 Ring indicator (RI) 0 = inactive 1 = activeB7 Receive line signal detect (RLSD) 0 = inactive 1 = active Layout of the second byte: B0 Data ready (DR)B1 Overrun error (OE)B2 Parity error (PE)B3 Framing error (FE)B4 Break interrupt (BI)B5 Transmitter holding register (THRE)B6 Transmitter empty (TEMT)B7 Error in RCVR FIFO ftdi pointer to ftdi_context status Pointer to store status information in. Must be two bytes. 0 : all fine -1 : unable to retrieve status information -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, FTDI_DEVICE_IN_REQTYPE, SIO_POLL_MODEM_STATUS_REQUEST, ftdi_context::index, ftdi_context::usb_read_timeout.
Referenced by ftdi_write_eeprom, Ftdi::Context::poll_modem_status.
int ftdi_setflowctrl(struct ftdi_context *ftdi, int flowctrl)
Set flowcontrol for ftdi chip ftdi pointer to ftdi_context flowctrl flow control to use. should be SIO_DISABLE_FLOW_CTRL, SIO_RTS_CTS_HS, SIO_DTR_DSR_HS or SIO_XON_XOFF_HS 0 : all fine -1 : set flow control failed -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, FTDI_DEVICE_OUT_REQTYPE, SIO_SET_FLOW_CTRL_REQUEST, ftdi_context::index, ftdi_context::usb_write_timeout.
Referenced by Ftdi::Context::set_flow_control.
int ftdi_setdtr_rts(struct ftdi_context *ftdi, int dtr, int rts)
Set dtr and rts line in one pass ftdi pointer to ftdi_context dtr DTR state to set line to (1 or 0) rts RTS state to set line to (1 or 0) 0 : all fine -1 : set dtr/rts failed -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, SIO_SET_DTR_HIGH, SIO_SET_DTR_LOW, SIO_SET_RTS_HIGH, SIO_SET_RTS_LOW, FTDI_DEVICE_OUT_REQTYPE, SIO_SET_MODEM_CTRL_REQUEST, ftdi_context::index, ftdi_context::usb_write_timeout.
Referenced by Ftdi::Context::set_modem_control.
int ftdi_setdtr(struct ftdi_context *ftdi, int state)
Set dtr line ftdi pointer to ftdi_context state state to set line to (1 or 0) 0 : all fine -1 : set dtr failed -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, SIO_SET_DTR_HIGH, SIO_SET_DTR_LOW, FTDI_DEVICE_OUT_REQTYPE, SIO_SET_MODEM_CTRL_REQUEST, ftdi_context::index, ftdi_context::usb_write_timeout.
Referenced by Ftdi::Context::set_dtr.
int ftdi_setrts(struct ftdi_context *ftdi, int state)
Set rts line ftdi pointer to ftdi_context state state to set line to (1 or 0) 0 : all fine -1 : set rts failed -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, SIO_SET_RTS_HIGH, SIO_SET_RTS_LOW, FTDI_DEVICE_OUT_REQTYPE, SIO_SET_MODEM_CTRL_REQUEST, ftdi_context::index, ftdi_context::usb_write_timeout.
Referenced by Ftdi::Context::set_rts.
int ftdi_set_event_char(struct ftdi_context *ftdi, unsigned char eventch, unsigned char enable)
Set the special event character ftdi pointer to ftdi_context eventch Event character enable 0 to disable the event character, non-zero otherwise 0 : all fine -1 : unable to set event character -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, FTDI_DEVICE_OUT_REQTYPE, SIO_SET_EVENT_CHAR_REQUEST, ftdi_context::index, ftdi_context::usb_write_timeout.
Referenced by Ftdi::Context::set_event_char.
int ftdi_set_error_char(struct ftdi_context *ftdi, unsigned char errorch, unsigned char enable)
Set error character ftdi pointer to ftdi_context errorch Error character enable 0 to disable the error character, non-zero otherwise 0 : all fine -1 : unable to set error character -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, FTDI_DEVICE_OUT_REQTYPE, SIO_SET_ERROR_CHAR_REQUEST, ftdi_context::index, ftdi_context::usb_write_timeout.
Referenced by Ftdi::Context::set_error_char.
int ftdi_eeprom_initdefaults(struct ftdi_context *ftdi, char *manufacturer, char *product, char *serial)
Init eeprom with default values for the connected device ftdi pointer to ftdi_context manufacturer String to use as Manufacturer product String to use as Product description serial String to use as Serial number description 0 : all fine -1 : No struct ftdi_context -2 : No struct ftdi_eeprom -3 : No connected device or device not yet opened
References ftdi_error_return, ftdi_context::eeprom, ftdi_context::usb_dev, ftdi_eeprom::vendor_id, ftdi_eeprom::use_serial, ftdi_context::type, TYPE_AM, TYPE_BM, TYPE_R, ftdi_eeprom::product_id, TYPE_4232H, TYPE_232H, ftdi_eeprom::usb_version, ftdi_eeprom::max_power, ftdi_eeprom::manufacturer, ftdi_eeprom::product, TYPE_2232C, TYPE_2232H, ftdi_eeprom::serial, ftdi_eeprom::size, ftdi_eeprom::cbus_function, CBUS_TXLED, CBUS_RXLED, CBUS_TXDEN, CBUS_PWREN, CBUS_SLEEP, CBUSH_TRISTATE, ftdi_eeprom::initialized_for_connected_device.
Referenced by Ftdi::Eeprom::init_defaults.
int ftdi_eeprom_build(struct ftdi_context *ftdi)
Build binary buffer from ftdi_eeprom structure. Output is suitable for ftdi_write_eeprom(). ftdi pointer to ftdi_context >=0 : size of eeprom user area in bytes -1 : eeprom size (128 bytes) exceeded by custom strings -2 : Invalid eeprom or ftdi pointer -3 : Invalid cbus function setting (FIXME: Not in the code?) -4 : Chip doesn't support invert (FIXME: Not in the code?) -5 : Chip doesn't support high current drive (FIXME: Not in the code?) -6 : No connected EEPROM or EEPROM Type unknown
References ftdi_error_return, ftdi_context::eeprom, ftdi_eeprom::buf, ftdi_eeprom::chip, ftdi_eeprom::size, ftdi_eeprom::manufacturer, ftdi_eeprom::product, ftdi_eeprom::serial, ftdi_context::type, TYPE_AM, TYPE_BM, TYPE_2232C, TYPE_R, TYPE_2232H, TYPE_4232H, TYPE_232H, FTDI_MAX_EEPROM_SIZE, ftdi_eeprom::vendor_id, ftdi_eeprom::product_id, ftdi_eeprom::self_powered, ftdi_eeprom::remote_wakeup, ftdi_eeprom::max_power, MAX_POWER_MILLIAMP_PER_UNIT, ftdi_eeprom::in_is_isochronous, ftdi_eeprom::out_is_isochronous, ftdi_eeprom::is_not_pnp, ftdi_eeprom::use_serial, USE_SERIAL_NUM, ftdi_eeprom::usb_version, ftdi_eeprom::use_usb_version, USE_USB_VERSION_BIT, ftdi_eeprom::channel_a_type, ftdi_eeprom::channel_a_driver, DRIVER_VCP, ftdi_eeprom::high_current_a, HIGH_CURRENT_DRIVE, ftdi_eeprom::channel_b_type, ftdi_eeprom::channel_b_driver, ftdi_eeprom::high_current_b, ftdi_eeprom::suspend_pull_downs, ftdi_eeprom::high_current, HIGH_CURRENT_DRIVE_R, ftdi_eeprom::invert, ftdi_eeprom::cbus_function, CBUS_BB, CBUS_TXLED, CBUS_RXLED, CBUS_TXDEN, CBUS_PWREN, CBUS_CLK6, CBUS_SLEEP, ftdi_eeprom::suspend_dbus7, SUSPEND_DBUS7_BIT, ftdi_eeprom::group0_drive, DRIVE_16MA, ftdi_eeprom::group0_schmitt, IS_SCHMITT, ftdi_eeprom::group0_slew, SLOW_SLEW, ftdi_eeprom::group1_drive, ftdi_eeprom::group1_schmitt, ftdi_eeprom::group1_slew, ftdi_eeprom::group2_drive, ftdi_eeprom::group2_schmitt, ftdi_eeprom::group2_slew, ftdi_eeprom::group3_drive, ftdi_eeprom::group3_schmitt, ftdi_eeprom::group3_slew, ftdi_eeprom::channel_c_driver, ftdi_eeprom::channel_d_driver, ftdi_eeprom::channel_a_rs485enable, CHANNEL_IS_RS485, ftdi_eeprom::channel_b_rs485enable, ftdi_eeprom::channel_c_rs485enable, ftdi_eeprom::channel_d_rs485enable, DRIVER_VCPH, ftdi_eeprom::powersave, POWER_SAVE_DISABLE_H, ftdi_eeprom::clock_polarity, FT1284_CLK_IDLE_STATE, ftdi_eeprom::data_order, FT1284_DATA_LSB, ftdi_eeprom::flow_control, FT1284_FLOW_CONTROL, set_ft232h_cbus.
Referenced by Ftdi::Eeprom::build.
int ftdi_eeprom_decode(struct ftdi_context *ftdi, int verbose)
Decode binary EEPROM image into an ftdi_eeprom structure. ftdi pointer to ftdi_context verbose Decode EEPROM on stdout 0 : all fine -1 : something went wrong FIXME: How to pass size? How to handle size field in ftdi_eeprom? FIXME: Strings are malloc'ed here and should be freed somewhere
References ftdi_eeprom::buf, ftdi_context::eeprom, ftdi_error_return, ftdi_eeprom::size, ftdi_eeprom::vendor_id, ftdi_eeprom::product_id, ftdi_eeprom::self_powered, ftdi_eeprom::remote_wakeup, ftdi_eeprom::max_power, MAX_POWER_MILLIAMP_PER_UNIT, ftdi_eeprom::in_is_isochronous, ftdi_eeprom::out_is_isochronous, ftdi_eeprom::suspend_pull_downs, ftdi_eeprom::use_serial, USE_SERIAL_NUM, ftdi_eeprom::use_usb_version, USE_USB_VERSION_BIT, ftdi_eeprom::usb_version, ftdi_eeprom::manufacturer, ftdi_eeprom::product, ftdi_eeprom::serial, ftdi_eeprom::channel_a_type, ftdi_context::type, TYPE_AM, TYPE_BM, ftdi_eeprom::chip, TYPE_2232C, ftdi_eeprom::channel_a_driver, DRIVER_VCP, ftdi_eeprom::high_current_a, HIGH_CURRENT_DRIVE, ftdi_eeprom::channel_b_type, ftdi_eeprom::channel_b_driver, ftdi_eeprom::high_current_b, TYPE_R, ftdi_eeprom::high_current, HIGH_CURRENT_DRIVE_R, ftdi_eeprom::invert, ftdi_eeprom::cbus_function, TYPE_2232H, TYPE_4232H, ftdi_eeprom::suspend_dbus7, SUSPEND_DBUS7_BIT, ftdi_eeprom::channel_c_driver, ftdi_eeprom::channel_d_driver, ftdi_eeprom::channel_a_rs485enable, CHANNEL_IS_RS485, ftdi_eeprom::channel_b_rs485enable, ftdi_eeprom::channel_c_rs485enable, ftdi_eeprom::channel_d_rs485enable, ftdi_eeprom::group0_drive, DRIVE_16MA, ftdi_eeprom::group0_schmitt, IS_SCHMITT, ftdi_eeprom::group0_slew, SLOW_SLEW, ftdi_eeprom::group1_drive, ftdi_eeprom::group1_schmitt, ftdi_eeprom::group1_slew, ftdi_eeprom::group2_drive, ftdi_eeprom::group2_schmitt, ftdi_eeprom::group2_slew, ftdi_eeprom::group3_drive, ftdi_eeprom::group3_schmitt, ftdi_eeprom::group3_slew, TYPE_232H, DRIVER_VCPH, ftdi_eeprom::clock_polarity, FT1284_CLK_IDLE_STATE, ftdi_eeprom::data_order, FT1284_DATA_LSB, ftdi_eeprom::flow_control, FT1284_FLOW_CONTROL, ftdi_eeprom::powersave, POWER_SAVE_DISABLE_H, ftdi_eeprom::is_not_pnp, CBUSH_CLK7_5, CBUS_BB.
int ftdi_get_eeprom_value(struct ftdi_context *ftdi, enum ftdi_eeprom_value value_name, int *value)
Get a value from the decoded EEPROM structure ftdi pointer to ftdi_context value_name Enum of the value to query value Pointer to store read value 0 : all fine -1 : Value doesn't exist
References VENDOR_ID, ftdi_context::eeprom, ftdi_eeprom::vendor_id, PRODUCT_ID, ftdi_eeprom::product_id, SELF_POWERED, ftdi_eeprom::self_powered, REMOTE_WAKEUP, ftdi_eeprom::remote_wakeup, IS_NOT_PNP, ftdi_eeprom::is_not_pnp, SUSPEND_DBUS7, ftdi_eeprom::suspend_dbus7, IN_IS_ISOCHRONOUS, ftdi_eeprom::in_is_isochronous, OUT_IS_ISOCHRONOUS, ftdi_eeprom::out_is_isochronous, SUSPEND_PULL_DOWNS, ftdi_eeprom::suspend_pull_downs, USE_SERIAL, ftdi_eeprom::use_serial, USB_VERSION, ftdi_eeprom::usb_version, USE_USB_VERSION, ftdi_eeprom::use_usb_version, MAX_POWER, ftdi_eeprom::max_power, CHANNEL_A_TYPE, ftdi_eeprom::channel_a_type, CHANNEL_B_TYPE, ftdi_eeprom::channel_b_type, CHANNEL_A_DRIVER, ftdi_eeprom::channel_a_driver, CHANNEL_B_DRIVER, ftdi_eeprom::channel_b_driver, CHANNEL_C_DRIVER, ftdi_eeprom::channel_c_driver, CHANNEL_D_DRIVER, ftdi_eeprom::channel_d_driver, CHANNEL_A_RS485, ftdi_eeprom::channel_a_rs485enable, CHANNEL_B_RS485, ftdi_eeprom::channel_b_rs485enable, CHANNEL_C_RS485, ftdi_eeprom::channel_c_rs485enable, CHANNEL_D_RS485, ftdi_eeprom::channel_d_rs485enable, CBUS_FUNCTION_0, ftdi_eeprom::cbus_function, CBUS_FUNCTION_1, CBUS_FUNCTION_2, CBUS_FUNCTION_3, CBUS_FUNCTION_4, CBUS_FUNCTION_5, CBUS_FUNCTION_6, CBUS_FUNCTION_7, CBUS_FUNCTION_8, CBUS_FUNCTION_9, HIGH_CURRENT, ftdi_eeprom::high_current, HIGH_CURRENT_A, ftdi_eeprom::high_current_a, HIGH_CURRENT_B, ftdi_eeprom::high_current_b, INVERT, ftdi_eeprom::invert, GROUP0_DRIVE, ftdi_eeprom::group0_drive, GROUP0_SCHMITT, ftdi_eeprom::group0_schmitt, GROUP0_SLEW, ftdi_eeprom::group0_slew, GROUP1_DRIVE, ftdi_eeprom::group1_drive, GROUP1_SCHMITT, ftdi_eeprom::group1_schmitt, GROUP1_SLEW, ftdi_eeprom::group1_slew, GROUP2_DRIVE, ftdi_eeprom::group2_drive, GROUP2_SCHMITT, ftdi_eeprom::group2_schmitt, GROUP2_SLEW, ftdi_eeprom::group2_slew, GROUP3_DRIVE, ftdi_eeprom::group3_drive, GROUP3_SCHMITT, ftdi_eeprom::group3_schmitt, GROUP3_SLEW, ftdi_eeprom::group3_slew, POWER_SAVE, ftdi_eeprom::powersave, CLOCK_POLARITY, ftdi_eeprom::clock_polarity, DATA_ORDER, ftdi_eeprom::data_order, FLOW_CONTROL, ftdi_eeprom::flow_control, CHIP_TYPE, ftdi_eeprom::chip, CHIP_SIZE, ftdi_eeprom::size, ftdi_error_return.
int ftdi_set_eeprom_value(struct ftdi_context *ftdi, enum ftdi_eeprom_value value_name, int value)
Set a value in the decoded EEPROM Structure No parameter checking is performed ftdi pointer to ftdi_context value_name Enum of the value to set value to set 0 : all fine -1 : Value doesn't exist -2 : Value not user settable
References VENDOR_ID, ftdi_context::eeprom, ftdi_eeprom::vendor_id, PRODUCT_ID, ftdi_eeprom::product_id, SELF_POWERED, ftdi_eeprom::self_powered, REMOTE_WAKEUP, ftdi_eeprom::remote_wakeup, IS_NOT_PNP, ftdi_eeprom::is_not_pnp, SUSPEND_DBUS7, ftdi_eeprom::suspend_dbus7, IN_IS_ISOCHRONOUS, ftdi_eeprom::in_is_isochronous, OUT_IS_ISOCHRONOUS, ftdi_eeprom::out_is_isochronous, SUSPEND_PULL_DOWNS, ftdi_eeprom::suspend_pull_downs, USE_SERIAL, ftdi_eeprom::use_serial, USB_VERSION, ftdi_eeprom::usb_version, USE_USB_VERSION, ftdi_eeprom::use_usb_version, MAX_POWER, ftdi_eeprom::max_power, CHANNEL_A_TYPE, ftdi_eeprom::channel_a_type, CHANNEL_B_TYPE, ftdi_eeprom::channel_b_type, CHANNEL_A_DRIVER, ftdi_eeprom::channel_a_driver, CHANNEL_B_DRIVER, ftdi_eeprom::channel_b_driver, CHANNEL_C_DRIVER, ftdi_eeprom::channel_c_driver, CHANNEL_D_DRIVER, ftdi_eeprom::channel_d_driver, CHANNEL_A_RS485, ftdi_eeprom::channel_a_rs485enable, CHANNEL_B_RS485, ftdi_eeprom::channel_b_rs485enable, CHANNEL_C_RS485, ftdi_eeprom::channel_c_rs485enable, CHANNEL_D_RS485, ftdi_eeprom::channel_d_rs485enable, CBUS_FUNCTION_0, ftdi_eeprom::cbus_function, CBUS_FUNCTION_1, CBUS_FUNCTION_2, CBUS_FUNCTION_3, CBUS_FUNCTION_4, CBUS_FUNCTION_5, CBUS_FUNCTION_6, CBUS_FUNCTION_7, CBUS_FUNCTION_8, CBUS_FUNCTION_9, HIGH_CURRENT, ftdi_eeprom::high_current, HIGH_CURRENT_A, ftdi_eeprom::high_current_a, HIGH_CURRENT_B, ftdi_eeprom::high_current_b, INVERT, ftdi_eeprom::invert, GROUP0_DRIVE, ftdi_eeprom::group0_drive, GROUP0_SCHMITT, ftdi_eeprom::group0_schmitt, GROUP0_SLEW, ftdi_eeprom::group0_slew, GROUP1_DRIVE, ftdi_eeprom::group1_drive, GROUP1_SCHMITT, ftdi_eeprom::group1_schmitt, GROUP1_SLEW, ftdi_eeprom::group1_slew, GROUP2_DRIVE, ftdi_eeprom::group2_drive, GROUP2_SCHMITT, ftdi_eeprom::group2_schmitt, GROUP2_SLEW, ftdi_eeprom::group2_slew, GROUP3_DRIVE, ftdi_eeprom::group3_drive, GROUP3_SCHMITT, ftdi_eeprom::group3_schmitt, GROUP3_SLEW, ftdi_eeprom::group3_slew, CHIP_TYPE, ftdi_eeprom::chip, POWER_SAVE, ftdi_eeprom::powersave, CLOCK_POLARITY, ftdi_eeprom::clock_polarity, DATA_ORDER, ftdi_eeprom::data_order, FLOW_CONTROL, ftdi_eeprom::flow_control, CHIP_SIZE, ftdi_error_return.
int ftdi_get_eeprom_buf(struct ftdi_context *ftdi, unsigned char *buf, int size)
Get the read-only buffer to the binary EEPROM content ftdi pointer to ftdi_context buf buffer to receive EEPROM content size Size of receiving buffer 0 : All fine -1 : struct ftdi_contxt or ftdi_eeprom missing -2 : Not enough room to store eeprom
References ftdi_context::eeprom, ftdi_error_return, FTDI_MAX_EEPROM_SIZE, ftdi_eeprom::buf.
int ftdi_set_eeprom_buf(struct ftdi_context *ftdi, const unsigned char *buf, int size)
Set the EEPROM content from the user-supplied prefilled buffer ftdi pointer to ftdi_context buf buffer to read EEPROM content size Size of buffer 0 : All fine -1 : struct ftdi_contxt or ftdi_eeprom of buf missing
References ftdi_context::eeprom, ftdi_error_return, FTDI_MAX_EEPROM_SIZE, ftdi_eeprom::buf.
int ftdi_read_eeprom(struct ftdi_context *ftdi)
Read eeprom ftdi pointer to ftdi_context 0 : all fine -1 : read failed -2 : USB device unavailable
References ftdi_eeprom::buf, ftdi_context::usb_dev, ftdi_error_return, ftdi_context::eeprom, FTDI_MAX_EEPROM_SIZE, FTDI_DEVICE_IN_REQTYPE, SIO_READ_EEPROM_REQUEST, ftdi_context::usb_read_timeout, ftdi_context::type, TYPE_R, ftdi_eeprom::size.
Referenced by Ftdi::Eeprom::read.
int ftdi_read_chipid(struct ftdi_context *ftdi, unsigned int *chipid)
Read the FTDIChip-ID from R-type devices ftdi pointer to ftdi_context chipid Pointer to store FTDIChip-ID 0 : all fine -1 : read failed -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, FTDI_DEVICE_IN_REQTYPE, SIO_READ_EEPROM_REQUEST, ftdi_context::usb_read_timeout.
Referenced by Ftdi::Eeprom::chip_id.
int ftdi_write_eeprom(struct ftdi_context *ftdi)
Write eeprom ftdi pointer to ftdi_context 0 : all fine -1 : read failed -2 : USB device unavailable -3 : EEPROM not initialized for the connected device;
References ftdi_context::usb_dev, ftdi_error_return, ftdi_context::eeprom, ftdi_eeprom::initialized_for_connected_device, ftdi_eeprom::buf, ftdi_usb_reset, ftdi_poll_modem_status, ftdi_set_latency_timer, ftdi_eeprom::size, FTDI_DEVICE_OUT_REQTYPE, SIO_WRITE_EEPROM_REQUEST, ftdi_context::usb_write_timeout.
Referenced by Ftdi::Eeprom::write.
int ftdi_erase_eeprom(struct ftdi_context *ftdi)
References ftdi_context::usb_dev, ftdi_error_return, ftdi_context::type, TYPE_R, ftdi_context::eeprom, ftdi_eeprom::chip, FTDI_DEVICE_OUT_REQTYPE, SIO_ERASE_EEPROM_REQUEST, ftdi_context::usb_write_timeout, SIO_WRITE_EEPROM_REQUEST, MAGIC, ftdi_read_eeprom_location.
Referenced by Ftdi::Eeprom::erase.
int ftdi_read_eeprom_location(struct ftdi_context *ftdi, int eeprom_addr, unsigned short *eeprom_val)
Read eeprom location ftdi pointer to ftdi_context eeprom_addr Address of eeprom location to be read eeprom_val Pointer to store read eeprom location 0 : all fine -1 : read failed -2 : USB device unavailable
References ftdi_context::usb_dev, ftdi_error_return, FTDI_DEVICE_IN_REQTYPE, SIO_READ_EEPROM_REQUEST, ftdi_context::usb_read_timeout.
Referenced by ftdi_write_eeprom_location, ftdi_erase_eeprom, Ftdi::Eeprom::read_location.
int ftdi_write_eeprom_location(struct ftdi_context *ftdi, int eeprom_addr, unsigned short eeprom_val)
Write eeprom location ftdi pointer to ftdi_context eeprom_addr Address of eeprom location to be written eeprom_val Value to be written 0 : all fine -1 : write failed -2 : USB device unavailable -3 : Invalid access to checksum protected area below 0x80 -4 : Device can't access unprotected area -5 : Reading chip type failed
References ftdi_context::usb_dev, ftdi_error_return, ftdi_context::type, TYPE_BM, TYPE_2232C, TYPE_2232H, TYPE_4232H, TYPE_232H, ftdi_read_eeprom_location, FTDI_DEVICE_OUT_REQTYPE, SIO_WRITE_EEPROM_REQUEST, ftdi_context::usb_write_timeout.
Referenced by Ftdi::Eeprom::write_location.
char* ftdi_get_error_string(struct ftdi_context *ftdi)
Get string representation for last error code ftdi pointer to ftdi_context Pointer to error string
References ftdi_context::error_str.
Referenced by Ftdi::Context::error_string, ftdi_readstream.